export { authService } from "./auth.service"
export { visitasService } from "./visitas.service"
export { docentesService } from "./docentes.service"
export { requerimientosService } from "./requerimientos.service"
export { evidenciasService } from "./evidencias.service"
export { sedesService } from "./sedes.service"
export { asignaturasService } from "./asignaturas.service"
export { responsablesService } from "./responsables.service"
export type { LoginRequest, LoginResponse } from "./auth.service"
export type { Visita, VisitaCreateData, VisitaProgramarData } from "./visitas.service"
export type { Docente } from "./docentes.service"
export type { RequerimientoVisita, RequerimientoUpdateRequest } from "./requerimientos.service"
export type { EvidenciaRequerimiento } from "./evidencias.service"
export type { Sede } from "./sedes.service"
export type { Asignatura } from "./asignaturas.service"
export type { Responsable } from "./responsables.service"
